INSERT INTO cards (name, rarity, price, set, card_type, language) VALUES
-- Holo Rares (16 Pokémon)
('Alakazam', 'Holo Rare', 15.00, 'Base Set', 'Pokémon', 'English'),
('Blastoise', 'Holo Rare', 40.00, 'Base Set', 'Pokémon', 'English'),
('Chansey', 'Holo Rare', 10.00, 'Base Set', 'Pokémon', 'English'),
('Charizard', 'Holo Rare', 150.00, 'Base Set', 'Pokémon', 'English'),
('Clefairy', 'Holo Rare', 12.00, 'Base Set', 'Pokémon', 'English'),
('Gyarados', 'Holo Rare', 20.00, 'Base Set', 'Pokémon', 'English'),
('Hitmonchan', 'Holo Rare', 8.00, 'Base Set', 'Pokémon', 'English'),
('Machamp', 'Holo Rare', 10.00, 'Base Set', 'Pokémon', 'English'),
('Magneton', 'Holo Rare', 7.00, 'Base Set', 'Pokémon', 'English'),
('Mewtwo', 'Holo Rare', 25.00, 'Base Set', 'Pokémon', 'English'),
('Nidoking', 'Holo Rare', 15.00, 'Base Set', 'Pokémon', 'English'),
('Ninetales', 'Holo Rare', 12.00, 'Base Set', 'Pokémon', 'English'),
('Poliwrath', 'Holo Rare', 10.00, 'Base Set', 'Pokémon', 'English'),
('Raichu', 'Holo Rare', 18.00, 'Base Set', 'Pokémon', 'English'),
('Venusaur', 'Holo Rare', 35.00, 'Base Set', 'Pokémon', 'English'),
('Zapdos', 'Holo Rare', 20.00, 'Base Set', 'Pokémon', 'English'),

-- Rares (16 Pokémon)
('Beedrill', 'Rare', 3.00, 'Base Set', 'Pokémon', 'English'),
('Dragonair', 'Rare', 5.00, 'Base Set', 'Pokémon', 'English'),
('Dugtrio', 'Rare', 2.50, 'Base Set', 'Pokémon', 'English'),
('Electabuzz', 'Rare', 4.00, 'Base Set', 'Pokémon', 'English'),
('Electrode', 'Rare', 3.00, 'Base Set', 'Pokémon', 'English'),
('Pidgeotto', 'Rare', 2.00, 'Base Set', 'Pokémon', 'English'),
('Arcanine', 'Uncommon', 1.50, 'Base Set', 'Pokémon', 'English'), -- Note: Often listed as Rare in some contexts, but Base Set has it as Uncommon
('Charmeleon', 'Uncommon', 1.00, 'Base Set', 'Pokémon', 'English'), -- Same note
('Dewgong', 'Uncommon', 1.00, 'Base Set', 'Pokémon', 'English'),
('Dratini', 'Uncommon', 0.80, 'Base Set', 'Pokémon', 'English'),
('Farfetch''d', 'Uncommon', 0.90, 'Base Set', 'Pokémon', 'English'),
('Growlithe', 'Uncommon', 0.70, 'Base Set', 'Pokémon', 'English'),
('Haunter', 'Uncommon', 1.20, 'Base Set', 'Pokémon', 'English'),
('Ivysaur', 'Uncommon', 1.50, 'Base Set', 'Pokémon', 'English'),
('Jynx', 'Uncommon', 0.80, 'Base Set', 'Pokémon', 'English'),
('Kadabra', 'Uncommon', 1.00, 'Base Set', 'Pokémon', 'English'),

-- Uncommons (32 total, continuing with Pokémon then Trainers)
('Machoke', 'Uncommon', 0.90, 'Base Set', 'Pokémon', 'English'),
('Magikarp', 'Uncommon', 0.80, 'Base Set', 'Pokémon', 'English'),
('Magmar', 'Uncommon', 0.90, 'Base Set', 'Pokémon', 'English'),
('Nidorino', 'Uncommon', 0.70, 'Base Set', 'Pokémon', 'English'),
('Poliwhirl', 'Uncommon', 0.80, 'Base Set', 'Pokémon', 'English'),
('Porygon', 'Uncommon', 1.00, 'Base Set', 'Pokémon', 'English'),
('Raticate', 'Uncommon', 0.70, 'Base Set', 'Pokémon', 'English'),
('Seel', 'Uncommon', 0.60, 'Base Set', 'Pokémon', 'English'),
('Wartortle', 'Uncommon', 1.20, 'Base Set', 'Pokémon', 'English'),
('Abra', 'Common', 0.50, 'Base Set', 'Pokémon', 'English'), -- Starts Commons, but listed here for flow
('Bulbasaur', 'Common', 1.00, 'Base Set', 'Pokémon', 'English'),
('Caterpie', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),
('Charmander', 'Common', 1.50, 'Base Set', 'Pokémon', 'English'),
('Diglett', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),
('Doduo', 'Common', 0.50, 'Base Set', 'Pokémon', 'English'),
('Drowzee', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),
('Gastly', 'Common', 0.60, 'Base Set', 'Pokémon', 'English'),

-- Commons (32 total, continuing)
('Koffing', 'Common', 0.50, 'Base Set', 'Pokémon', 'English'),
('Machop', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),
('Magnemite', 'Common', 0.50, 'Base Set', 'Pokémon', 'English'),
('Metapod', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),
('Nidoran♂', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),
('Onix', 'Common', 0.60, 'Base Set', 'Pokémon', 'English'),
('Pidgey', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),
('Pikachu', 'Common', 2.00, 'Base Set', 'Pokémon', 'English'),
('Poliwag', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),
('Ponyta', 'Common', 0.50, 'Base Set', 'Pokémon', 'English'),
('Rattata', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),
('Sandshrew', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),
('Squirtle', 'Common', 1.20, 'Base Set', 'Pokémon', 'English'),
('Starmie', 'Common', 0.50, 'Base Set', 'Pokémon', 'English'),
('Staryu', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),
('Tangela', 'Common', 0.50, 'Base Set', 'Pokémon', 'English'),
('Voltorb', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),
('Vulpix', 'Common', 0.60, 'Base Set', 'Pokémon', 'English'),
('Weedle', 'Common', 0.40, 'Base Set', 'Pokémon', 'English'),

-- Trainers (26 total, mix of Rares, Uncommons, Commons)
('Bill', 'Common', 0.30, 'Base Set', 'Trainer', 'English'),
('Energy Removal', 'Common', 0.40, 'Base Set', 'Trainer', 'English'),
('Energy Retrieval', 'Uncommon', 0.50, 'Base Set', 'Trainer', 'English'),
('Gust of Wind', 'Common', 0.30, 'Base Set', 'Trainer', 'English'),
('Potion', 'Common', 0.20, 'Base Set', 'Trainer', 'English'),
('Super Potion', 'Uncommon', 0.40, 'Base Set', 'Trainer', 'English'),
('Switch', 'Common', 0.30, 'Base Set', 'Trainer', 'English'),
('Clefairy Doll', 'Rare', 1.00, 'Base Set', 'Trainer', 'English'),
('Computer Search', 'Rare', 3.00, 'Base Set', 'Trainer', 'English'),
('Devolution Spray', 'Rare', 0.80, 'Base Set', 'Trainer', 'English'),
('Imposter Professor Oak', 'Rare', 1.50, 'Base Set', 'Trainer', 'English'),
('Item Finder', 'Rare', 2.00, 'Base Set', 'Trainer', 'English'),
('Lass', 'Rare', 1.20, 'Base Set', 'Trainer', 'English'),
('Pokémon Breeder', 'Rare', 1.00, 'Base Set', 'Trainer', 'English'),
('Pokémon Center', 'Uncommon', 0.60, 'Base Set', 'Trainer', 'English'),
('Pokémon Flute', 'Uncommon', 0.50, 'Base Set', 'Trainer', 'English'),
('Pokémon Trader', 'Rare', 1.50, 'Base Set', 'Trainer', 'English'),
('Professor Oak', 'Uncommon', 0.80, 'Base Set', 'Trainer', 'English'),
('Scoop Up', 'Rare', 1.20, 'Base Set', 'Trainer', 'English'),
('Super Energy Removal', 'Rare', 1.00, 'Base Set', 'Trainer', 'English'),
('Defender', 'Uncommon', 0.50, 'Base Set', 'Trainer', 'English'),
('Full Heal', 'Uncommon', 0.40, 'Base Set', 'Trainer', 'English'),
('Maintenance', 'Uncommon', 0.50, 'Base Set', 'Trainer', 'English'),
('PlusPower', 'Uncommon', 0.60, 'Base Set', 'Trainer', 'English'),
('Pokédex', 'Uncommon', 0.50, 'Base Set', 'Trainer', 'English'),
('Revive', 'Uncommon', 0.60, 'Base Set', 'Trainer', 'English'),

-- Energy (6 total, no rarity in Base Set)
('Double Colorless Energy', 'Uncommon', 1.00, 'Base Set', 'Energy', 'English'),
('Fighting Energy', 'Common', 0.10, 'Base Set', 'Energy', 'English'),
('Fire Energy', 'Common', 0.10, 'Base Set', 'Energy', 'English'),
('Grass Energy', 'Common', 0.10, 'Base Set', 'Energy', 'English'),
('Lightning Energy', 'Common', 0.10, 'Base Set', 'Energy', 'English'),
('Psychic Energy', 'Common', 0.10, 'Base Set', 'Energy', 'English'),
('Water Energy', 'Common', 0.10, 'Base Set', 'Energy', 'English');
